[package]
name = "chot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"

[[bin]]
name = "server"
path = "src/bin/server/main.rs"

[[bin]]
name = "client"
path = 'src/bin/client/main.rs'

[lib]
name = "chot"
path = "src/lib/lib.rs"
